[package]
name = "hfuzz-bp7"
version = "0.1.0"
authors = ["gh0st <1264131+gh0st42@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5"
bp7 = { path = ".." }
